---
title: "Data Formatting"
output: html_document
---
This document is the unused code for formatting conn.log. 

## Code used to label conn.log
```{r}
for (i in length(conn)){
  conn$malicious <- NA
  conn$atcktype <- '-'
}
```

```{r}
x = nrow(conn) %/% 10000
i=1
for (i in c(1:10000)){
  conn1[[i]] = conn[((i-1)*x+1):(i*x),] 
}
conn1[[10001]] = conn[((10000)*x+1):nrow(conn),]
```

### Main approach 1
```{r}
x = nrow(conn) %/% 5
i=1
j=1
table1 = conn[((j-1)*x+1):(j*x+1),]
table2 = conn[((j)*x+1):((j+1)*x+1),]
Next = FALSE
while(i < nrow(snort)){
  Next=FALSE
  if (snort$Port[i]){
    if (nrow(table1[table1$ts == snort$ts[i] & table1$srcIP == snort$srcIP[i] & table1$dstIP == snort$dstIP[i] & table1$srcPort == snort$srcPort[i] & table1$dstPort == snort$dstPort[i],]) > 0){
      if (table1[table1$ts == snort$ts[i] & table1$srcIP == snort$srcIP[i] & table1$dstIP == snort$dstIP[i] & table1$srcPort == snort$srcPort[i] & table1$dstPort == snort$dstPort[i],'malicious'] != TRUE){
        table1[table1$ts == snort$ts[i] & table1$srcIP == snort$srcIP[i] & table1$dstIP == snort$dstIP[i] & table1$srcPort == snort$srcPort[i] & table1$dstPort == snort$dstPort[i],'malicious'] <- TRUE 
      }else{
        if (nrow(table2[table2$ts == snort$ts[i] & table2$srcIP == snort$srcIP[i] & table2$dstIP == snort$dstIP[i] & table2$srcPort == snort$srcPort[i] & table2$dstPort == snort$dstPort[i],]) > 0){
        table2[table2$ts == snort$ts[i] & table2$srcIP == snort$srcIP[i] & table2$dstIP == snort$dstIP[i] & table2$srcPort == snort$srcPort[i] & table2$dstPort == snort$dstPort[i],'malicious'] <- TRUE
        Next <- TRUE
        }
        i=i+1
      }
    }else {
      if (nrow(table2[table2$ts == snort$ts[i] & table2$srcIP == snort$srcIP[i] & table2$dstIP == snort$dstIP[i] & table2$srcPort == snort$srcPort[i] & table2$dstPort == snort$dstPort[i],]) > 0){
        table2[table2$ts == snort$ts[i] & table2$srcIP == snort$srcIP[i] & table2$dstIP == snort$dstIP[i] & table2$srcPort == snort$srcPort[i] & table2$dstPort == snort$dstPort[i],'malicious'] <- TRUE
        i=i+1
        Next <- TRUE
      }else{
        i=i+1
      } 
    }
  }else{
    if (nrow(table1[table1$ts == snort$ts[i] & table1$srcIP == snort$srcIP[i] & table1$dstIP == snort$dstIP[i],]) > 0){
      if (table1[table1$ts == snort$ts[i] & table1$srcIP == snort$srcIP[i] & table1$dstIP == snort$dstIP[i],'malicious'] != TRUE){
        table1[table1$ts == snort$ts[i] & table1$srcIP == snort$srcIP[i] & table1$dstIP == snort$dstIP[i],'malicious'] <- TRUE 
      }else{
        if (nrow(table2[table2$ts == snort$ts[i] & table2$srcIP == snort$srcIP[i] & table2$dstIP == snort$dstIP[i],]) > 0){
          table2[table2$ts == snort$ts[i] & table2$srcIP == snort$srcIP[i] & table2$dstIP == snort$dstIP[i],'malicious'] <- TRUE
          Next <- TRUE
        }
        i=i+1
      }
    }else {
      if (nrow(table2[table2$ts == snort$ts[i] & table2$srcIP == snort$srcIP[i] & table2$dstIP == snort$dstIP[i],]) > 0){
        table2[table2$ts == snort$ts[i] & table2$srcIP == snort$srcIP[i] & table2$dstIP == snort$dstIP[i],'malicious'] <- TRUE
        i=i+1
        Next <- TRUE
      }else{
        i=i+1
      } 
    }
  }
  if (Next){
    print(j)
    table1 <- table2
    if (j == 1){
      malconn <- table1
      table2 = conn[((j+1)*x+1):((j+2)*x+1),]
    }else{
      if (j < 3) { 
        table2 = conn[((j+1)*x+1):((j+2)*x+1),]
      }else if (j == 3){
        table2 = conn[((4)*x+1):nrow(conn),]
      }
      malconn <- rbind(malconn,table1)
    }
    j=j+1
  }
}
```


### Main approach 2
```{r}
conn2 = {}
i=1
j=1
table1 = conn1[[j]]
table2 = conn1[[j+1]]
while(i < nrow(snort)){
  if (snort$Port[i]){
    if (nrow(table1[table1$ts == snort$ts[i] & table1$srcIP == snort$srcIP[i] & table1$dstIP == snort$dstIP[i] & table1$srcPort == snort$srcPort[i] & table1$dstPort == snort$dstPort[i],]) > 0){
      if (table1[table1$ts == snort$ts[i] & table1$srcIP == snort$srcIP[i] & table1$dstIP == snort$dstIP[i] & table1$srcPort == snort$srcPort[i] & table1$dstPort == snort$dstPort[i],'malicious'] != TRUE){
        table1[table1$ts == snort$ts[i] & table1$srcIP == snort$srcIP[i] & table1$dstIP == snort$dstIP[i] & table1$srcPort == snort$srcPort[i] & table1$dstPort == snort$dstPort[i],'malicious'] <- TRUE 
      }else{
        if (nrow(table2[table2$ts == snort$ts[i] & table2$srcIP == snort$srcIP[i] & table2$dstIP == snort$dstIP[i] & table2$srcPort == snort$srcPort[i] & table2$dstPort == snort$dstPort[i],]) > 0){
          table2[table2$ts == snort$ts[i] & table2$srcIP == snort$srcIP[i] & table2$dstIP == snort$dstIP[i] & table2$srcPort == snort$srcPort[i] & table2$dstPort == snort$dstPort[i],'malicious'] <- TRUE
          conn2 <- bind_rows(conn2,table1)
          j=j+1
          print(j)
          table1 = table2
          if(j<100001){
            table2 = conn1[[j+1]]  
          }
        }
        i=i+1
      }
    }else {
      if (nrow(table2[table2$ts == snort$ts[i] & table2$srcIP == snort$srcIP[i] & table2$dstIP == snort$dstIP[i] & table2$srcPort == snort$srcPort[i] & table2$dstPort == snort$dstPort[i],]) > 0){
        table2[table2$ts == snort$ts[i] & table2$srcIP == snort$srcIP[i] & table2$dstIP == snort$dstIP[i] & table2$srcPort == snort$srcPort[i] & table2$dstPort == snort$dstPort[i],'malicious'] <- TRUE
        conn2 <- bind_rows(conn2,table1)
        j=j+1
        print(j)
        table1 = table2
        if(j<100001){
          table2 = conn1[[j+1]]  
        }
        i=i+1
      }else{
        k=j+2
        while (nrow(conn1[[k]][conn1[[k]]$ts == snort$ts[i] & conn1[[k]]$srcIP == snort$srcIP[i] & conn1[[k]]$dstIP == snort$dstIP[i] & conn1[[k]]$srcPort == snort$srcPort[i] & conn1[[k]]$dstPort == snort$dstPort[i],]) == 0 & k <= 10000){
          k=k+1
        }
        if (nrow(conn1[[k]][conn1[[k]]$ts == snort$ts[i] & conn1[[k]]$srcIP == snort$srcIP[i] & conn1[[k]]$dstIP == snort$dstIP[i] & conn1[[k]]$srcPort == snort$srcPort[i] & conn1[[k]]$dstPort == snort$dstPort[i],]) > 0){
          conn2 <- bind_rows(conn2,table1)
          for (l in c(j+1:k-1)){
            conn2 <-  bind_rows(conn2,conn1[[l]]) 
          }
          j=k
          print(j)
          table1 = conn1[[j]]
          if(j<100001){
            table2 = conn1[[j+1]]  
          }
          table1[table1$ts == snort$ts[i] & table1$srcIP == snort$srcIP[i] & table1$dstIP == snort$dstIP[i] & table1$srcPort == snort$srcPort[i] & table1$dstPort == snort$dstPort[i],'malicious'] <- TRUE
        }
      }
      i=i+1
    }
  }else{
    if (nrow(table1[table1$ts == snort$ts[i] & table1$srcIP == snort$srcIP[i] & table1$dstIP == snort$dstIP[i],]) > 0){
      if (table1[table1$ts == snort$ts[i] & table1$srcIP == snort$srcIP[i] & table1$dstIP == snort$dstIP[i],'malicious'] != TRUE){
        table1[table1$ts == snort$ts[i] & table1$srcIP == snort$srcIP[i] & table1$dstIP == snort$dstIP[i],'malicious'] <- TRUE 
      }else{
        if (nrow(table2[table2$ts == snort$ts[i] & table2$srcIP == snort$srcIP[i] & table2$dstIP == snort$dstIP[i],]) > 0){
          table2[table2$ts == snort$ts[i] & table2$srcIP == snort$srcIP[i] & table2$dstIP == snort$dstIP[i],'malicious'] <- TRUE
          conn2 <- bind_rows(conn2,table1)
          j=j+1
          print(j)
          table1 = table2
          if(j<100001){
            table2 = conn1[[j+1]]  
          }
        }
        i=i+1
      }
    }else {
      if (nrow(table2[table2$ts == snort$ts[i] & table2$srcIP == snort$srcIP[i] & table2$dstIP == snort$dstIP[i],]) > 0){
        table2[table2$ts == snort$ts[i] & table2$srcIP == snort$srcIP[i] & table2$dstIP == snort$dstIP[i],'malicious'] <- TRUE
        conn2 <- bind_rows(conn2,table1)
        j=j+1
        print(j)
        table1 = table2
        if(j<100001){
          table2 = conn1[[j+1]]  
        }
        i=i+1
      }else{
        k=j+2
        while (nrow(conn1[[k]][conn1[[k]]$ts == snort$ts[i] & conn1[[k]]$srcIP == snort$srcIP[i] & conn1[[k]]$dstIP == snort$dstIP[i],]) == 0 & k <= 10000){
          k=k+1
        }
        if (nrow(conn1[[k]][conn1[[k]]$ts == snort$ts[i] & conn1[[k]]$srcIP == snort$srcIP[i] & conn1[[k]]$dstIP == snort$dstIP[i],]) > 0){
          conn2 <- bind_rows(conn2,table1)
          for (l in c(j+1:k-1)){
            conn2 <-  bind_rows(conn2,conn1[[l]]) 
          }
          j=k
          print(j)
          table1 = conn1[[j]]
          if(j<100001){
            table2 = conn1[[j+1]]  
          }
          table1[table1$ts == snort$ts[i] & table1$srcIP == snort$srcIP[i] & table1$dstIP == snort$dstIP[i],'malicious'] <- TRUE
        }
      }
      i=i+1
    }
  }
}
```